package main

import (
	"log"
	"os"

	"github.com/supabase-community/supabase-go"
)

var dbClient *supabase.Client

// InitDatabase initializes the connection using the supabase-go library
func InitDatabase() {
	supabaseUrl := os.Getenv("SUPABASE_URL")
	supabaseKey := os.Getenv("SUPABASE_SERVICE_KEY") // Use service key for admin write access

	if supabaseUrl == "" || supabaseKey == "" {
		log.Fatal("SUPABASE_URL and SUPABASE_SERVICE_KEY must be set")
	}

	client, err := supabase.NewClient(supabaseUrl, supabaseKey, &supabase.ClientOptions{})
	if err != nil {
		log.Fatalf("cannot initialize supabase client: %v", err)
	}

	dbClient = client
	log.Println("Supabase Client Initilized successfully")
}

// MatchRecord represents the matches table
type MatchRecord struct {
	ID        string `json:"id,omitempty"` // UUID generated by DB usually
	RoomCode  string `json:"room_code"`
	Status    string `json:"status"`
}

// PlayerRecord represents the match_players table
type PlayerRecord struct {
	MatchID     string `json:"match_id"`
	UserID      string `json:"user_id"`
	ScoreTimeMs *int   `json:"score_time_ms"`
	Score       *int   `json:"score"` // New field for calculated points
	IsWinner    bool   `json:"is_winner"`
}

// SaveMatchResults saves the room and player scores to Supabase
func SaveMatchResults(roomCode string, players map[string]*Player) {
	if dbClient == nil {
		log.Println("Error: dbClient is nil, cannot save results")
		return
	}

	// 1. Insert Match
	matchRecord := MatchRecord{
		RoomCode: roomCode,
		Status:   "finished",
	}

	// We use the REST API via the client
	var returnedMatch []MatchRecord
	_, err := dbClient.From("matches").Insert(matchRecord, false, "", "", "").ExecuteTo(&returnedMatch)
	
	if err != nil || len(returnedMatch) == 0 {
		log.Printf("Error inserting match: %v", err)
		return
	}
	matchID := returnedMatch[0].ID

	// 2. Prepare Match Players & determine Winner
	var playerRecords []PlayerRecord
	var bestTime *int
	var winnerUserID string

	// Find the best time first to determine the winner
	for _, p := range players {
		if p.ScoreTimeMs != nil {
			if bestTime == nil || *p.ScoreTimeMs < *bestTime {
				bestTime = p.ScoreTimeMs
				winnerUserID = p.UserID
			}
		}
	}

	// Build records
	for _, p := range players {
		isWinner := p.UserID == winnerUserID && bestTime != nil
		
		// Logic point sederhana: 100.000 (Base Score Maksimal) dikurangi nilai time dalam ms
		// Jadi kalau dia selesai dalam 5.000 ms (5 detik), nilainya = 95.000 Poin.
		// Jika ScoreTimeMs > 100.000, batasi skor di minimum 0 (atau 100).
		var calculatedScore *int
		if p.ScoreTimeMs != nil {
			baseScore := 100000
			score := baseScore - *p.ScoreTimeMs
			if score < 0 {
				score = 0
			}
			calculatedScore = &score
		}
		
		record := PlayerRecord{
			MatchID:     matchID,
			UserID:      p.UserID, // Assuming this is UUID from frontend
			ScoreTimeMs: p.ScoreTimeMs,
			Score:       calculatedScore,
			IsWinner:    isWinner,
		}
		playerRecords = append(playerRecords, record)
	}

	// 3. Insert Match Players
	var returnedPlayers []PlayerRecord
	_, err = dbClient.From("match_players").Insert(playerRecords, false, "", "", "").ExecuteTo(&returnedPlayers)

	if err != nil {
		log.Printf("Error inserting match_players: %v", err)
		return
	}

	log.Printf("Successfully saved match %s results for %d players", roomCode, len(returnedPlayers))
}
